BingoDraw/BingoDraw/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as users_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', users_views.register, name='register'),
    path('profile/<str:user>/', users_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html' ), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html' ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('polls/', include('polls.urls')),
    path('bingo/', include('bingo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BingoDraw/bingo/urls.py
from django.urls import path

from . import views

app_name = 'bingo'
urlpatterns = [
    # ex: /bingo/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /bingo/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

BingoDraw/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote', views.vote, name='vote'),
    # ex: /polls/new/
    path('new/', views.QuestionCreateView.as_view(), name='question-create'),
    # ex: /polls/5/update/
    path('<int:pk>/update/', views.QuestionUpdateView.as_view(), name='update'),
    # ex: /polls/5/delete/
    path('<int:pk>/delete/', views.QuestionDeleteView.as_view(), name='delete'),
    # ex: /polls/user
    path('<str:username>', views.UserPollListView.as_view(), name='user-polls'),
]

BingoDraw/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # return the sum of votes for all choices
    def total_votes(self):
        total = 0
        for x in self.choices.all():
            total += x.votes
        return total

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

BingoDraw/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.db.models import F
from django.views import generic
from django.utils import timezone
from django.contrib.auth import mixins
from django.forms.models import inlineformset_factory
from django.contrib.auth.models import User

from bootstrap_datepicker_plus.widgets import DateTimePickerInput

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    paginate_by = 5

    def get_queryset(self):
        """Return the questions previously posted (no future dates) and order by date desc."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


class UserPollListView(generic.ListView):
    model = Question
    template_name = 'polls/user_polls.html'
    context_object_name = 'user_polls_list'
    paginate_by = 5

    def get_queryset(self):
        """Return the last five published questions."""
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Question.objects.filter(
            pub_date__lte=timezone.now(), author=user
        ).order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


# Formset to be included in QuestionCreateView
ChoiceFormset = inlineformset_factory(
    Question, Choice, fields=('choice_text',), extra=2
)

class QuestionCreateView(mixins.LoginRequiredMixin, generic.CreateView):
    model = Question
    template_name = 'polls/question_form.html'
    fields = ['question_text', 'pub_date']

    def get_form(self):
        """Add date picker to the form"""
        form = super(QuestionCreateView, self).get_form()
        form.fields['pub_date'].widget = DateTimePickerInput()
        return form

    def form_valid(self, form):
        context = self.get_context_data()
        form.instance.author = self.request.user
        choices = context["choices"]
        self.object = form.save()
        if choices.is_valid():
            choices.instance = self.object
            choices.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        # overwrite context data to include ChoiceFormset
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["choices"] = ChoiceFormset(self.request.POST)
        else:
            data["choices"] = ChoiceFormset()
        return data

    def get_success_url(self):
        return reverse('polls:index')


class QuestionUpdateView(mixins.LoginRequiredMixin, mixins.UserPassesTestMixin, generic.UpdateView):
    model = Question
    template_name = 'polls/question_form.html'
    fields = ['question_text', 'pub_date']


    def get_form(self):
        """Add date picker to the form"""
        form = super(QuestionUpdateView, self).get_form()
        form.fields['pub_date'].widget = DateTimePickerInput()
        return form

    def form_valid(self, form):
        context = self.get_context_data()
        choices = context["choices"]
        self.object = form.save()
        if choices.is_valid():
            choices.instance = self.object
            choices.save()
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        # overwrite context data to include ChoiceFormset
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["choices"] = ChoiceFormset(self.request.POST, instance=self.object)
        else:
            data["choices"] = ChoiceFormset(instance=self.object)
        return data

    def get_success_url(self):
        return reverse('polls:index')

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.author:
            return True
        return False


class QuestionDeleteView(mixins.LoginRequiredMixin, mixins.UserPassesTestMixin, generic.DeleteView):
    model = Question
    template_name = 'polls/question_confirm_delete.html'

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.author:
            return True
        return False

    def get_success_url(self):
        return reverse('polls:index')


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choices.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

BingoDraw/polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!-- CSS Stylesheet -->
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
        <!-- jQuery Library -->
        <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
        <!-- Bootstrap Framework -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!-- moment.js -->
<!--    <script type="text/javascript" src="{{ STATIC_URL }} /static/moment.js"></script>-->

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% if title %}
            <title>Polls - {{ title }}</title>
        {% else %}
            <title>Polls</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
              <a class="navbar-brand mr-4" href="{% url 'polls:index' %}">Polls</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                      <a class="nav-item nav-link" href="{% url 'polls:index' %}">Home</a>
                      <a class="nav-item nav-link disabled" tabindex="-1" aria-disabled="true" href="#">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                      {% if user.is_authenticated %}
                          <a class="nav-item nav-link" href="{% url 'polls:question-create' %}">Create Poll</a>
                          <a class="nav-item nav-link" href="{% url 'profile' user %}">Profile</a>
                          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                      {% else %}
                          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                      {% endif %}
                    </div>
                </div>
            </div>
          </nav>
        </header>
        <main role="main" class="container">
          <div class="row">
            <div class="col-md-8">
              {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
              {% endif %}
              {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
              <div class="content-section">
                <h3>Applications</h3>
                <p class='text-muted'>Other applications
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="#">Bingo Draw</a></li>
                    <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="#">Randomizer</a></li>
                    <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="#">Dice Roll</a></li>
                    <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="#">Ranked Choice Vote</a></li>
                  </ul>
                </p>
              </div>
            </div>
          </div>
        </main>
    </body>
</html>

BingoDraw/polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block content %}
    <legend><h1>{{ question.question_text }}</h1></legend>
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'polls:user-polls' question.author.username %}">{{ question.author }}</a>
                <small class="text-muted">{{ question.pub_date }}</small>
            </div>
                <form action="{% url 'polls:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <fieldset>
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                        {% for choice in question.choices.all %}
                            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                        {% endfor %}
                    </fieldset>
                    <input type="submit" value="Vote">
                </form>
            <div>
                {% if question.author == user %}
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'polls:update' question.id %}">Update</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'polls:delete' question.id %}">Delete</a>
                {% endif %}
            </div>
        </div>
    </article>
{% endblock content %}


BingoDraw/polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block content %}
    <h1>Choose a Question</h1>

    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'polls:user-polls' question.author.username %}">{{ question.author }}</a>
                  <small class="text-muted">on {{ question.pub_date|date:"F d, Y" }}</small>
                </div>
                <h2><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></h2>
                <small class="text-muted">Total Votes: {{ question.total_votes }}</small>
              </div>
            </article>
        {% endfor %}
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'+3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        {% endif %}
    {% else %}
        <article class="media content-section">
          <div class="media-body">
            <h2>No polls are available.</h2>
          </div>
        </article>
    {% endif %}
{% endblock content %}

BingoDraw/polls/templates/polls/question_confirm_delete.html
{% extends "polls/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Delete Question</legend>
      <h2>Are you sure you want to delete this poll?</h2>
      <h2>"{{ question.question_text }}"</h2>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
      <a class="btn btn-outline-secondary" href="{% url 'polls:detail' question.id %}">Cancel</a>
    </div>
  </form>
</div>

{% endblock content %}

BingoDraw/polls/templates/polls/question_form.html
{% extends "polls/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block content %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Create/Update a Poll</legend>
      <div id="form_set">
        {% bootstrap_form form %}
      </div>
      <legend class="border-bottom mb-4">Choices</legend>
        {{ choices.management_form }}
        {% for choice_form in choices %}
          <div id="form_set_choice">
            {% bootstrap_form choice_form %}
          </div>
        {% endfor %}
    </fieldset>
    <input class="btn btn-outline-info" type="button" value="Add More" id="add_more">
    <div id="empty_form" style="display:none">
      <fieldset class="form-group">
          {{ serviceFormset.empty_form|crispy }}
      </fieldset>
    </div>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Post</button>
    </div>
  </form>
</div>
<script type="text/javascript">
  $('#add_more').click(function() {
      var form_idx = $('#choices-TOTAL_FORMS').val();
      $('#form_set_choice').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
      $('#choices-TOTAL_FORMS').val(parseInt(form_idx) + 1);
  });
</script>
{% endblock content %}

BingoDraw/polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% block content %}
  <h1>{{ question.question_text }}</h1>
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'polls:user-polls' question.author.username %}">{{ question.author }}</a>
        <small class="text-muted">{{ question.pub_date }}</small>
      </div>
      <ul class="list-group">
        {% for choice in question.choices.all %}
            <li class="list-group-item list-group-item-light">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
        <p><a href="{% url 'polls:detail' question.id %}">Vote again?</a></p>
      </ul>
    </div>
  </article>

{% endblock content %}

BingoDraw/polls/templates/polls/user_polls.html
{% extends "polls/base.html" %}
{% block content %}
    <h1 class="mb-3">Questions by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>

    {% if user_polls_list %}
        {% for question in user_polls_list %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'polls:user-polls' question.author.username %}">{{ question.author }}</a>
                  <small class="text-muted">on {{ question.pub_date|date:"F d, Y" }}</small>
                </div>
                <h2><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></h2>
                <small class="text-muted">Total Votes: {{ question.total_votes }}</small>
              </div>
            </article>
        {% endfor %}
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'+3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        {% endif %}
    {% else %}
        <article class="media content-section">
          <div class="media-body">
            <h2>No polls are available.</h2>
          </div>
        </article>
    {% endif %}
{% endblock content %}