BingoDraw/BingoDraw/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as users_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', users_views.register, name='register'),
    path('profile/<str:user>/', users_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html' ), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html' ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('polls/', include('polls.urls')),
    path('bingo/', include('bingo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BingoDraw/bingo/urls.py
from django.urls import path

from . import views

app_name = 'bingo'
urlpatterns = [
    # ex: /bingo/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /bingo/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

BingoDraw/bingo/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Card(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})


class Tile(models.Model):
    card = models.ForeignKey(Card, related_name='tiles', on_delete=models.CASCADE)
    tile_text = models.CharField(max_length=200)

    def __str__(self):
        return self.tile_text

BingoDraw/bingo/views.py
from django.views import generic
from django.utils import timezone

from .models import Card


class IndexView(generic.ListView):
    template_name = 'bingo/index.html'
    context_object_name = 'bingo_index'
    paginate_by = 5

    def get_queryset(self):
        """Return the questions previously posted (no future dates) and order by date desc."""
        return Card.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Card
    template_name = 'bingo/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Card.objects.filter(pub_date__lte=timezone.now())

BingoDraw/bingo/templates/bingo/detail.html
{% extends "polls/base.html" %}
{% block content %}
<legend><h1>{{ card.title }}</h1></legend>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <small class="text-muted">{{ card.pub_date }}</small>
        </div>
        <fieldset>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for tile in card.tiles.all %}
            <li class="list-group-item list-group-item-light">{{ tile.tile_text }}</li>
            {% endfor %}
        </fieldset>
    </div>
</article>
{% endblock content %}

BingoDraw/bingo/templates/bingo/index.html
{% extends "polls/base.html" %}
{% block content %}
<h1>Choose a Bingo Card</h1>
{% if bingo_index %}
{% for card in bingo_index %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <small class="text-muted">created on {{ card.pub_date|date:"F d, Y" }}</small>
        </div>
        <h2><a href="{% url 'bingo:detail' card.id %}">{{ card.title }}</a></h2>
    </div>
</article>
{% endfor %}
{% if is_paginated %}
{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'+3' %}
<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}
{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}
{% endif %}
{% else %}
<article class="media content-section">
    <div class="media-body">
        <h2>No bingo cards are available.</h2>
    </div>
</article>
{% endif %}
{% endblock content %}